# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: E-Commerce CI/CD Pipeline

on:
  push:
    branches: 
      - master
      - feature/*
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore    
    - name: Upload E-Commerce App build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-build-artifacts
        path:
          ./home/runner/work/E-CommerceApp/E-CommerceApp/E-CommerceApp/bin/Debug/net8.0/E-CommerceApp.dll
    - name: Upload User Service build artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: user-service-build-artifacts
        path: ./home/runner/work/E-CommerceApp/E-CommerceApp/UserMicroService/bin/Debug/net8.0/UserMicroService.dll
    - name: Upload User Service Unit Tests build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: user-service-ut-build-artifacts
        path: ./home/runner/work/E-CommerceApp/E-CommerceApp/UserMicroService.UnitTests/bin/Debug/net8.0/UserMicroService.UnitTests.dll

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Download E-Commerce App build artifacts
      uses: actions/download-artifact@v3
      with:
          name: app-build-artifacts
          path: ./downloaded-artifacts
    - name: Download User Service build artifacts
      uses: actions/download-artifact@v3
      with:
          name: user-service-build-artifacts
          path: ./downloaded-artifacts 
    - name: Download User Service Unit Tests build artifacts
      uses: actions/download-artifact@v3
      with:
          name: user-service-ut-build-artifacts
          path: ./downloaded-artifacts
    - name: Test
      run: dotnet test ./downloaded-artifacts/UserMicroService.UnitTests.dll --no-build --verbosity normal --max-parallel 4
